doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            item_id: Spisywarka\Infrastructure\Doctrine\Type\ItemIdType
            category_id: Spisywarka\Infrastructure\Doctrine\Type\CategoryIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Spisywarka:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Spisywarka/Infrastructure/Doctrine/config'
                prefix: 'Spisywarka\Domain\Model'
                alias: Spisywarka
