framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface:
        default_bus: command.bus

        # Create buses
        buses:
            command.bus: ~
            event.bus:
                default_middleware: allow_no_handlers